### ISSUE TITLE
Multiple rules for the same class not being merged

### ISSUE THREAD

**Issue by alexlibby** [morishitter/atcss#4]
Hi,

I've tried out the first example shown on the front page of this site - whilst atcss is compiling, it isn't producing the output I would expect to see?

I've used both atcss at a command prompt level, and as a gulp plugin - on a Windows environment, I get this output:

```
.imprt {
  color: blue;
}

.class {
  /*
   * @base
   * @constant
   */
  font-size: 12px;
  padding: 8px 16px;
}

.too-long-and-ugly-selector-name {
  /*
   * @base
   */
  color: red;
}

.class {
  /*
   * @use .base-1
   */
  background-color: green;
}

.too-long-and-ugly-selector-name {
  /*
   * @use .base-2
   */
  margin: 10px;
}
```

..which doesn't match the output on the front page of this site, where the .too-long-and-ugly-selector-name class rules are clearly shown as having been merged into one rule. Can you please confirm which is expected behavior?

**Comment by msaktype** [comment]
It dose not reproduce in my environment (Mac OS X 10.10, Node v4.2.3, atcss v2.0.0). Sorry, I don't have any windows machines. Can you tell me your Node and atcss versions?

**Comment by alexlibby** [comment]
No problem - I downloaded the current release of atcss that is available from this site; my version of Node is 4.1.1, with NPM at version 3.5.3.

If it is not reproducible, and given I have a slightly older version of Node, is it worth me upgrading to see if this fixes the issue?

**Comment by alexlibby** [comment]
I've tried updating to the latest version of Node (4.2.6) - unfortunately the result is still the same for me; it isn't merging the two instances of the ".too-long-and-ugly-selector-name" rule into one.

**Comment by msaktype** [comment]
@alexlibby I just released css-annotation v0.6.2, a dependency module of atcss. Please re-install atcss and confirm again.

**Comment by alexlibby** [comment]
Sorry - it's still the same for me: it is not merging the rules together.

I had to reinstall both atcss and gulp-atcss before I could get any compilation to complete. I got an warning around fsevents, which I've seen before - I understand that this relates to adding code that is Mac-specific; is it possible this _may_ be causing an issue? The text of the warning is this:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.7
npm WARN enoent ENOENT: no such file or directory, open 'C:\wamp\www\postcss\nod
e_modules\cls\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\wamp\www\postcss\nod
e_modules\cosmiconfig\package.json'
npm WARN postcss@1.0.0 No repository field.
```

Not sure if this has any bearing on the issue, but thought it best you be aware...

EDIT: A question - once code is compiled, would you expect to see the comments still appear? Granted, I understand why they are required for compilation, but once the code is compiled, do they actually serve any purpose?

**Comment by vintprox** [comment]
@alexlibby Regarding to comments: that's the good question for [cssnano](https://cssnano.co/). It purges all comments and extraneous whitespaces from CSS.
